/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-08-03 07:17:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import UserProfile.UserProfile;

public final class userProfileInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/niikp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153370682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1533280530523L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("UserProfile.UserProfile");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Данные пользователя</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://bootstraptema.ru/plugins/2015/bootstrap3/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://bootstraptema.ru/plugins/font-awesome/4-4-0/font-awesome.min.css\" />\r\n");
      out.write("<script src=\"http://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<script src=\"http://bootstraptema.ru/plugins/2015/b-v3-3-6/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\tbody{background:url(http://bootstraptema.ru/images/bg/bg-1.png)}\r\n");
      out.write("\r\n");
      out.write("\t#main {\r\n");
      out.write("\t\tbackground-color: #f2f2f2;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t\t-webkit-border-radius: 4px;\r\n");
      out.write("\t\t-moz-border-radius: 4px;\r\n");
      out.write("\t\t-ms-border-radius: 4px;\r\n");
      out.write("\t\t-o-border-radius: 4px;\r\n");
      out.write("\t\tborder-radius: 4px;\r\n");
      out.write("\t\tborder-bottom: 4px solid #ddd;\r\n");
      out.write("\t}\r\n");
      out.write("\t#real-estates-detail #author img {\r\n");
      out.write("\t\t-webkit-border-radius: 100%;\r\n");
      out.write("\t\t-moz-border-radius: 100%;\r\n");
      out.write("\t\t-ms-border-radius: 100%;\r\n");
      out.write("\t\t-o-border-radius: 100%;\r\n");
      out.write("\t\tborder-radius: 100%;\r\n");
      out.write("\t\tborder: 5px solid #ecf0f1;\r\n");
      out.write("\t\tmargin-bottom: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#real-estates-detail .sosmed-author i.fa {\r\n");
      out.write("\t\twidth: 30px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tborder: 2px solid #bdc3c7;\r\n");
      out.write("\t\tcolor: #bdc3c7;\r\n");
      out.write("\t\tpadding-top: 6px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-default .panel-heading {\r\n");
      out.write("\t\tbackground-color: #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\t#real-estates-detail .slides li img {\r\n");
      out.write("\t\theight: 450px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\r\n");
      out.write("\t");

	UserProfile userProfileInfo = (UserProfile) request.getAttribute("userProfileInfo");
    //System.out.println("id = " + userProfileInfo.getUserId() + " email: " + userProfileInfo.getEmail());
            
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<div class=\"row\" id=\"real-estates-detail\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<header class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>Пользователь сайта</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\" id=\"author\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"https://b1.gmbox.ru/c/148071.815xp.jpg\" width=\"300\" height=250 >\r\n");
      out.write("\t\t\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfileInfo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" &nbsp; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfileInfo.secondName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Email: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfileInfo.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"label label-warning\">Российская Федерация</small>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Статус пользователя</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"sosmed-author\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\" title=\"Facebook\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\" title=\"Twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-google-plus\" title=\"Google Plus\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-linkedin\" title=\"Linkedin\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-8 col-md-8 col-xs-12\">\r\n");
      out.write("\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"myTab\" class=\"nav nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Вот тут условие,если пользователь зарегестрирован,видит Мои данные и Редактировать, если нет,то О пользователе и Отправить СОобщение -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#detail\" data-toggle=\"tab\">О пользователе</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\"><a href=\"#contact\" data-toggle=\"tab\">Отправить сообщение</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/niikp/userProfile?action=update\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\" data-original-title=\"\" title=\"\">Редактировать профиль</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- КОнец -->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade active in\" id=\"detail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>История профиля</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-th-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Зарегистрирован:</td><td>12-06-2016</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Последняя активность:</td><td>12-06-2016 / 09:11</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Страна:</td><td>Россия</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Город:</td><td>Волгоград</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Пол:</td><td>Мужской</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Дата Рождения:</td><td> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userProfileInfo.birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Семейное положение:</td><td>Женат</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Рейтинг пользователя:</td><td><i class=\"fa fa-star\" style=\"color:red\"></i> <i class=\"fa fa-star\" style=\"color:red\"></i> <i class=\"fa fa-star\" style=\"color:red\"></i> <i class=\"fa fa-star\" style=\"color:red\"></i> 4/5</td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr><td class=\"active\">Плагин рейтинга:</td><td><a href=\"http://bootstraptema.ru/stuff/plugins_bootstrap/improvement/bootstrap_star_rating/12-1-0-73\" target=\"_blank\">http://goo.gl/bGGXuw</a></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label>Ваше имя</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control rounded\" placeholder=\"Укажите Ваше Имя\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label>Ваш телефон</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control rounded\" placeholder=\"(+7)(095)123456\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label>E-mail адрес</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control rounded\" placeholder=\"Ваш Е-майл\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"> Согласен с условиями\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label>Текст Вашего сообщения</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control rounded\" style=\"height: 100px;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">Текст сообщения будет отправлен пользователю</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\" data-original-title=\"\" title=\"\">Отправить</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.main -->\r\n");
      out.write("</div><!-- /.container -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /userProfileInfo.jsp(63,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("userProfileInfo");
      // /userProfileInfo.jsp(63,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/userProfileInfo.jsp(63,1) '${userProfileInfo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userProfileInfo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
